[package]
name = "adventofcode2020"
version = "0.1.0"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2021"

[dependencies]
anyhow = "1.0.57"
regex = "1.5.6"
lazy_static = "1.4.0"
itertools = "0.10.3"
nom = "7.1.1"
string-intern = "0.1.7"

