[package]
name = "adventofcode2020"
version = "0.1.0"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
regex = "1.4.2"
lazy_static = "1.4.0"
itertools = "0.9.0"
nom = "6.0.1"
string-intern = "0.1.7"
