#!/bin/bash

LCOV=$(mktemp -p . --suffix .lcov)

set -e -x

export CARGO_INCREMENTAL='0'
export RUSTFLAGS='-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
export RUSTDOCFLAGS='-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
cargo test --all-features --no-fail-fast --bins
grcov . -s . --binary-path ./target/debug/deps -t lcov --branch --ignore-not-existing -o "$LCOV"
chmod a+r "$LCOV"
echo "::set-output name=report::$LCOV"

